### ISSUE TITLE
Scoreboard Issues: reporting incorrectly; graphic artifacts in chart; "15" next to tootip

### ISSUE THREAD

**Issue by rdylanwalker** [kentcdodds/kentcdodds.com#157]
Issue 1: Text says one thing... chart says another:

![image](https://user-images.githubusercontent.com/4922876/136111993-ab559656-671b-4929-9b29-010d7565d04d.png)

![image](https://user-images.githubusercontent.com/4922876/136112007-2b348a1f-26ff-40d1-84c0-fd071df8b5e8.png)

Issue 2: After hovering, the chart shows some sort of left-over artifact color.  You can see it as a small yellow dot in the screenshot.  I'm using latest Chrome on Windows at 1440p.

Issue 3: There is a "15" next to the tooltip.  Unsure what that is for?

**Comment by kentcdodds** [comment]
Hi @rdylanwalker,

> Issue 1:

Did you click the "what's this?" link? It'll explain how the ranking system works. It's not just by reads because that would favor larger teams unfairly.

> Issue 2:

I'm afraid this is a browser rendering bug and there's nothing we can really do about it :( Hopefully it'll get fixed eventually by Chrome.

> Issue 3:

Click the "what's this?" link and it'll explain what that is :)

Thanks!

**Comment by rdylanwalker** [comment]
Hi @kentcdodds 

I did not read the description :(  I guess the graph was just not intuitive to me... which is why you explain it. Maybe this issue can be re-tasked into something like "Design methods to make stats chart initially intuitive". For example, adding a "% Read By Team" to the tooltip? Or maybe adding a split-bar: bar 1 = total reads, bar 2 = total team members?

For Issue 2 above, while it may be Chrome specific, I _feel_ like some clever CSS could fix it, possibly by adding an "invisible" layer (a color that matches the background) that expands _opposite_ of the bar.  So as the colored bar is shrinking, the "invisible" bar is filling back over where the colored bar was.  It's obviously not a big deal, but Chrome may never fix it.  They're still some scroll-fix code I have in projects where Chrome and FireFox handle scroll pixels differently :(

**Comment by kentcdodds** [comment]
I could probably make the stats more clear 👍

**Comment by kentcdodds** [comment]
Also, it looks like the number in there is incorrect as well 😅 Gotta look into this a bit 🙃

**Comment by kentcdodds** [comment]
An idea occurred to me that it might be useful to show the actual values of active members and recent reads on the team page. I'll probably do that. Because it definitely is surprising that the yellow team is in the lead by so much with fewer reads, but they have fewer team members so it makes sense when factoring in the rules.

**Comment by smeijer** [comment]
What if you wouldn't show the total read count, but just the relative percentage of all reads?

```
100 / sum(blue, red, yellow) * hoveredTeam
```

**Comment by kentcdodds** [comment]
Yeah, I actually do show the percentage if you hit ALT while hovering. I think I should swap the default there.

**Comment by rdylanwalker** [comment]
Yeah, without knowing the full data it's hard for me to know, but it does seem odd to report raw numbers when the score is weighted.  Perhaps you can report the "weighted score" on the chart so that it is immediately clear to readers _why_ [team] is in the lead.  Then, for transparency, the "What's this" could spell out the exact formula (without me having to check the source code) so the math can be checked more easily and/or understood in a direct way.

If the "weight" is simply a [number of read by team]/[number on team] * 100 (i.e., a percentage), then why not just report that on the chart?

Also, for now at least, I'm not sure the animation (which also has a graphic bug in Chrome) is helping.  My opinion:
1. It's bothersome to me to have to hover to see data on such a simple chart (it's not like hovering gives me _more_ data or a breakdown or something).
2. It might not be as accessible for screen-readers, etc. (though I've not tested this... just my intuition on these things from experience).
3. (edit) It's also a pain for anything "on hover" with mobile/touch devices because you have to long-press it.  So each bar has to be long-pressed to get all of the information. (edit 2) Just checked on mobile it's a single tap, so better than long-press, but still 3 taps to get the simple data out.  Couldn't figure out the alt-press on mobile.

I guess you have to ask yourself what the animation _adds_ to the site to make it worth keeping as animation.

Maybe unpopular opinion here because of all the work you've put into it, but maybe remove the chart?  Keep the "The [team] is winning!" and borders and all of that (makes the site a bit more "fun") and replace the chart with some sort of "hover" on the "[team]" color that shows other team placements.  Sometimes simple UI is better UX.

Quick mock up:
https://codesandbox.io/s/autumn-cache-nv74k?file=/index.html

Happy to contribute some commits once you have and idea on the direction you want to take.

**Comment by kentcdodds** [comment]
Thanks for the feedback. I like the stats the way they are (this isn't a sunk cost thing, I just like them as they are). I'm changing to show the ranking itself rather than the total number of reads. I think that'll clear up some confusion and then I can improve the "what's this" explainer and maybe show the full actual data as well.

I tried it with a screen reader and there's some stuff I'll work on to improve that experience a bit, but it's actually pretty good as-is.

**Comment by rdylanwalker** [comment]
@kentcdodds Closing this issue.  I think my concerns have been addressed.  If additional issues arise or other changes to the charts are desired then those can be more focused, new issues.

Thanks for the quick feedback and code!
