### ISSUE TITLE
Scroll position is not restored when navigating back to site

### ISSUE THREAD

**Issue by zdhz** [kentcdodds/kentcdodds.com#213]
Hello 👋 

The vertical scroll position in the browser on both desktop and mobile is not restored when navigating back in the browser. Tested on the /blog and /uses page, this can be really time consuming having to re-scroll back to the previous place when clicking through the various links on your site.

Steps to reproduce:
- Navigate to https://kcd.im/uses
- Scroll down and click external link
- Click back button in browser

Expected:
- Scroll position returned to previous place

Actual:
- Scroll position returned to top of page

As far as I'm aware this is default browser behaviour, so there must be something preventing this from happening.

Browser:
- MacOS: Brave (Version 1.31.88) / Chrome (Version 95.0.4638.69)
- iOS: Chrome

Thanks!

**Comment by ljbc1994** [comment]
Getting this as well, believe this is happening because when you click on "Load more articles" it doesn't update the url query with the number of articles shown (this could be used to render the list that the user has viewed). 

So when you go back it only renders the initial list therefore the scroll position is lost and you end up at the bottom of the page.

**Comment by kentcdodds** [comment]
Thanks! Scroll support will be built-into Remix soon so hopefully that will fix these issues.

For the blog post page, that's actually a great point. I should probably update the query string as you load more so when you go back it renders the same number of posts. I'll keep this issue open until I add that 👍

**Comment by kentcdodds** [comment]
This has been built-into Remix and should now be fixed :)
