### ISSUE TITLE
Incorrect URL showing in twitter:image and og:image meta tags

### ISSUE THREAD

**Issue by joshfarrant** [kentcdodds/kentcdodds.com#271]
## Summary

When sharing a post, the generated image can sometimes include an incorrect url

![image](https://user-images.githubusercontent.com/6840861/148762745-d87a8db4-f4d2-4a37-bb9f-af7ac0409fa5.png)

## Repro Steps

1. Navigate to a post - Note the correct `twitter:image` and `og:image` meta tags.
2. Navigate back to /blog 
3. Navigate to a different post - Note the `twitter:image` and `og:image` still include references to the previous post's URL.

## Resolution

I've had a look around and nothing's jumping out at me, so I'm unsure why this is happening.

If you have any idea of where to start looking I'd be more than happy to find and fix the issue myself and put a PR in 🙂

**Comment by kentcdodds** [comment]
Hi @joshfarrant,

Yeah, I know what's going on. Once you land on a page, I determine the request origin and path and pass that along to the root loader. That information remains the same until it's revalidated.

In practical scenarios it doesn't actually matter because these images are only ever requested on full-document requests. So the only people who will notice the image is wrong is people opening their devtools like you 😉

I've fixed it for mdx pages just for the heck of it, though I just realized in typing this that I actually *broke* it for non-blog post pages 😆 Reverting that. We're just fine as-is 😅

**Comment by joshfarrant** [comment]
Hey @kentcdodds - Appreciate the breakdown, thank you!

> So the only people who will notice the image is wrong is people opening their devtools like you 😉

Sounds like I've been rumbled! I was snooping your meta tags to see what some sensible defaults should be for my own site 😄

Amazing site, thank you for making it open source. It's been as useful a learning tool as the actual Remix docs 🙌

**Comment by kentcdodds** [comment]
I'm glad to hear it :) Thanks!
