### ISSUE TITLE
Ignore periods in gmail usernames

### ISSUE THREAD

**Issue by alecglen** [kentcdodds/kentcdodds.com#317]
Gmail ignores periods in usernames, so `alecglen@gmail.com` is equivalent to `alec.glen@gmail.com`.
https://support.google.com/mail/answer/7436150

It would be nice if the site's login flow was aware of this convention to avoid the scenario below:

1. I put the period in my email address when I created my account. Fast-forward X months, I'm signing in on a new machine.
2. I enter my email, but without the period this time around.
3. I get the email as expected, but the button link is to create a new account rather than to sign in to mine.
4. Repeat 2-3 a few times before realizing what's going on.

**Comment by kentcdodds** [comment]
Unfortunately this is tricky because I lookup emails in the database as they're entered and I've got a bunch of emails in the database already that have dots in it. So I'd have to do a migration to remove all the dots in the database so when you provide me one with dots I can remove it before doing the lookup.

I'm afraid I don't have the bandwidth for this.

What I recommend is putting the email you used in your password manager so you don't have this issue in the future.
