### ISSUE TITLE
When clicking "call kent" link in footer, scroll position stays at bottom of page

### ISSUE THREAD

**Issue by johtso** [kentcdodds/kentcdodds.com#338]

**Comment by schiaro98** [comment]
Something tell me that is this piece of code on
[ https://github.com/kentcdodds/kentcdodds.com/blob/main/app/routes/calls.tsx](url)
that gives this behaviour. Can't setup the project locally for trying, can someone provide?

`export const handle: KCDHandle & {id: string} = {
  id: 'calls',
  restoreScroll: false,
}`

Trying with `restoreScroll: true` can be the fastest solution.

**Comment by kentcdodds** [comment]
I need to spend some time working on the scroll. That `restoreScroll` config is custom (I added it on purpose). The problem is if you choose between different episodes on that page it is a route change and normally with route changes you want to scroll up to the top. I need to figure out a good way to have the link decide whether the scroll should happen instead.

**Comment by tylermercer** [comment]
Just ran into this on the blog page as well, I believe. Two thoughts just off the top of my head:

* You could use a URL hash for different podcast episodes instead of a route. This seems like a nice a web-idiomatic approach to me, seeing as they're different sections on the same page rather than being separate pages.
* You could modify your restoreScroll config to take a function that accepts the to and from routes and returns a bool. Vue follows a similar pattern in its route guards.

**Comment by kentcdodds** [comment]
The next version of React Router will solve this problem for me. I'm just going to wait for that to be released. It shouldn't be too much longer :) Thanks!

**Comment by ledenis** [comment]
There is the same issue for the "Chats Podcast" link in the footer.

**Comment by kentcdodds** [comment]
This has finally been fixed 🎉
