### ISSUE TITLE
Login in mobile failing in iOS

### ISSUE THREAD

**Issue by kimile** [kentcdodds/kentcdodds.com#371]
I'm getting a _Sign in link invalid. Please request a new one._ when clicking the link directly. I'm able to log in if I copy/paste the URL directly into Safari (the browser I requested to log in), but the default behavior is to open it on the in-app browser.

Steps to replicate:
1. Request a login link
2. Open the link in Gmail mobile app
3. Verify that it opened on the in-app browser (didn't jump to Safari/Chrome)
4. You should be redirected to the login page with the error message: _Sign in link invalid. Please request a new one._

Versions:
- iOS version is 15.6.1
- Gmail App version 6.0.220807

Changing Gmail settings does solve the problem (... > Settings > Default apps > Check _Default browser app_)

Poking around I realized that the direct cause for the problem is that in [this](https://github.com/kentcdodds/kentcdodds.com/blob/main/app/utils/prisma.server.ts#L174) block, `sessionLinkCode` is `null`.

However, even working around that code block, the user would still get logged in to the in-app browser instead of the external browser (which should be what he would expect).

**Comment by kentcdodds** [comment]
Hi @kimile!

Thanks for walking me through this.

The way it is currently is required for security reasons. There are workarounds I could implement (like sending a temporary code and having them enter the code rather than clicking the link). But this isn't high priority for me so I'm not going to do that.

Thanks!
